# site name
prefixName: Yukino
siteName:
# favicon and site master avatar
favicon: /images/favicon.ico
avatar: /img/yukino/avatar/a26.ico
url: /
description: やはり俺の青春ラブコメはまちがっている
cdn: https://cdn.staticaly.com/gh/Yukino831143/CDN@master
pjax: 1
# 1开启
mathjax: 0

notice: 我的青春恋爱物语果然有问题。完   正在更新中...
lazyloadImg: https://cdn.staticaly.com/gh/Yukino831143/CDN@master/img/loader/orange.progress-bar-stripe-loader.svg

menus:
  首页: { path: /, fa: fa-fort-awesome faa-shake }
  归档: { path: /archives, fa: fa-archive faa-shake, submenus: {
          #指定 hexo_sakuru/public/ 下资源读取，fa是配置的对应图标
          技术: { path: /categories/技术/, fa: fa-code },
          生活: { path: /categories/生活/, fa: fa-file-text-o },
          #资源: { path: /categories/资源/, fa: fa-cloud-download },
          随想: { path: /categories/随想/, fa: fa-commenting-o },
          #转载: { path: /categories/转载/, fa: fa-book },
          番剧: { path: /categories/番剧/, fa: fa-film faa-vertical },
          读书: { path: /categories/读书/, fa: fa-th-list faa-bounce },
          歌单: { path: /music/, fa: fa-headphones },
        } }

  # 清单:
  #   {
  #     path: javascript:;,
  #     fa: fa-list-ul faa-vertical,
  #     submenus:
  #       {
  #         书单: { path: /tags/悦读/, fa: fa-th-list faa-bounce },
  #         番组: { path: /bangumi/, fa: fa-film faa-vertical },
  #         歌单: { path: /music/, fa: fa-headphones },
  #         图集: { path: /tags/图集/, fa: fa-photo },
  #       },
  #   }
  留言板: { path: /comment/, fa: fa-pencil-square-o faa-tada }
  #友人帐: { path: /links/, fa: fa-link faa-shake }
  赞赏: { path: /donate/, fa: fa-heart faa-pulse }
  关于:
    {
      path: /,
      fa: fa-leaf faa-wrench,
      submenus:
        {
          我？: { path: /about/, fa: fa-meetup },
          主题: { path: /theme-sakura/, fa: iconfont icon-sakura },
          Lab: { path: /lab/, fa: fa-cogs },
        },
    }
  #客户端: { path: /client/, fa: fa-android faa-vertical }
  #RSS: { path: /atom.xml, fa: fa-rss faa-pulse }

# Home page sort type: -1: newer first，1: older first.
homePageSortType: -1
# Home page article shown number)
homeArticleShown: 10
# 背景图片 更好的修改
bg:
  - https://cdn.staticaly.com/gh/Yukino831143/CDN@master/img/cover/1.webp
  - https://cdn.staticaly.com/gh/Yukino831143/CDN@master/img/cover/2.webp
  - https://cdn.staticaly.com/gh/Yukino831143/CDN@master/img/cover/3.webp
  - https://cdn.staticaly.com/gh/Yukino831143/CDN@master/img/cover/4.webp
  - https://cdn.staticaly.com/gh/Yukino831143/CDN@master/img/cover/5.webp
  - https://cdn.staticaly.com/gh/Yukino831143/CDN@master/img/cover/6.webp
  - https://cdn.staticaly.com/gh/Yukino831143/CDN@master/img/cover/7.webp
  - https://cdn.staticaly.com/gh/Yukino831143/CDN@master/img/cover/8.webp

# 背景图片样式 空 原图效果 filter-dim 阴影 filter-grid 横条 filter-dot 点点
bgclass: filter-dot

# startdash url, title, desc img
startdash:
  - {
      url: /theme-sakura/,
      title: Sakura,
      desc: 基于hexo,
      img: /img/yukino/dash/2.png,
    }
  - {
      url: https://github.com/Yukino831143,
      title: github,
      desc: 博主的github,
      img: /img/yukino/dash/1.png,
    }
  - { url: /, title: ACG, desc: 二次元, img: /img/yukino/dash/3.png }

# your site build time or founded date
siteBuildingTime: 06/04/2020

#social  url, img PC端配置
social:
  github: { url: /#, img: /img/social/github.png }
  jianshu: { url: /#, img: /img/social/jianshu.png }
  sina: { url: /#, img: /img/social/sina.png }
  wangyiyun: { url: /#, img: /img/social/wangyiyun.png }
  zhihu: { url: /#, img: /img/social/zhihu.png }
  email: { url: /#, img: /img/social/email.svg }
  wechat:
    #{ url: /#, qrcode: /img/custom/wechat.jpg, img: /img/social/wechat.png }
    {
      url: /#,
      qrcode: /img/yukino/social/wechat.png,
      img: /img/social/wechat.png,
    }
#social  url, img 移动端配置
msocial:
  github: { url: https://github.com/Yukino831143, fa: fa-github, color: 333 }
  weibo:
    { url: http://weibo.com/mashirozx?is_all=1, fa: fa-weibo, color: dd4b39 }
  qq:
    {
      url: https://wpa.qq.com/msgrd?v=3&uin=954655431&site=qq&menu=yes,
      fa: fa-qq,
      color: 25c6fe,
    }

donate:
  paypal: /#
  alipay: /img/yukino/appreciation/aplipay.png
  wechat: /img/yukino/appreciation/aplipay.png
  wechatSQ: /img/yukino/appreciation/aplipay.png

# 视频地址为https://cdn.jsdelivr.net/gh/honjun/hojun@1.2/Unbroken.mp4，配置如下
movies:
  url: https://cdn.staticaly.com/gh/Yukino831143/CDN@master/img/yukino/video
  # 多个视频用逗号隔开，随机获取。支持的格式目前已知MP4,Flv。其他的可以试下，不保证有用
  name: yukino_360p.mp4

aplayer:
  id: 363423188
  server: netease
  type: playlist
  fixed: true
  autoplay: false
  loop: all
  order: random
  preload: auto
  volume: 0.7
  mutex: true

# Valine
valine: true
v_appId: 4asHXF3SLvCKEfXTHBmYKjpi-MdYXbMMI
v_appKey: xXS4NNFP7X7Su7AIwt86pHXj
